package gg.sona.msl.ir

enum class BuiltinVariable(val isInput: Boolean) {
    Position(false),
    PointSize(false),
    ClipDistance(false),
    CullDistance(false),
    Layer(false),
    ViewportIndex(false),
    VertexId(true),
    InstanceId(true),
    BaseVertex(true),
    BaseInstance(true),
    FragCoord(true),
    FrontFacing(true),
    PointCoord(true),
    SampleId(true),
    SampleMaskIn(true),
    SampleMaskOut(false),
    FragDepth(false),
    FragStencil(false),
    PrimitiveId(true),
    LayerIn(true),
    ViewportIndexIn(true),
    BarycentricCoord(true),
    GlobalInvocationId(true),
    LocalInvocationId(true),
    LocalInvocationIndex(true),
    WorkgroupId(true),
    NumWorkgroups(true),
    SubgroupLocalInvocationId(true),
    SubgroupId(true),
    SubgroupSize(true),
    NumSubgroups(true),
    ViewIndex(true),
}
