package gg.sona.msl.ir

enum class Intrinsic(val isPure: Boolean = true) {
    FAbs,
    FSign,
    Floor,
    Ceil,
    Round,
    Rint,
    Trunc,
    Fract,
    Sqrt,
    Rsqrt,
    Sin,
    Cos,
    Tan,
    Asin,
    Acos,
    Atan,
    Atan2,
    Sinh,
    Cosh,
    Tanh,
    Asinh,
    Acosh,
    Atanh,
    Exp,
    Exp2,
    Exp10,
    Log,
    Log2,
    Log10,
    Pow,
    Powr,
    Fma,
    FMin,
    FMax,
    FClamp,
    Mix,
    Step,
    Smoothstep,
    Saturate,
    Fmod,
    Ldexp,
    FrexpMantissa,
    FrexpExponent,
    Copysign,
    Fdim,
    Sinpi,
    Cospi,
    Tanpi,
    IsNan,
    IsInf,
    IsFinite,
    IsNormal,
    SignBit,
    SAbs,
    SAbsDiff,
    UAbsDiff,
    SAddSat,
    UAddSat,
    SSubSat,
    USubSat,
    SClamp,
    UClamp,
    SMin,
    SMax,
    UMin,
    UMax,
    Clz,
    Ctz,
    Popcount,
    ReverseBits,
    SExtractBits,
    UExtractBits,
    InsertBits,
    SHAdd,
    UHAdd,
    SRHAdd,
    URHAdd,
    SMulHi,
    UMulHi,
    Rotate,
    Dot,
    Cross,
    Length,
    Distance,
    Normalize,
    Reflect,
    Refract,
    FaceForward,
    Transpose,
    Determinant,
    All,
    Any,
    Dfdx(isPure = false),
    Dfdy(isPure = false),
    Fwidth(isPure = false),
    PackUnorm4x8,
    PackSnorm4x8,
    PackUnorm2x16,
    PackSnorm2x16,
    UnpackUnorm4x8,
    UnpackSnorm4x8,
    UnpackUnorm2x16,
    UnpackSnorm2x16,
    ThreadgroupBarrier(isPure = false),
    SimdgroupBarrier(isPure = false),
    Discard(isPure = false),
    SimdSum(isPure = false),
    SimdProduct(isPure = false),
    SimdMin(isPure = false),
    SimdMax(isPure = false),
    SimdAnd(isPure = false),
    SimdOr(isPure = false),
    SimdXor(isPure = false),
    SimdPrefixInclusiveSum(isPure = false),
    SimdPrefixInclusiveProduct(isPure = false),
    SimdPrefixExclusiveSum(isPure = false),
    SimdPrefixExclusiveProduct(isPure = false),
    SimdBroadcast(isPure = false),
    SimdBroadcastFirst(isPure = false),
    SimdShuffle(isPure = false),
    SimdShuffleUp(isPure = false),
    SimdShuffleDown(isPure = false),
    SimdShuffleXor(isPure = false),
    SimdBallot(isPure = false),
    SimdAll(isPure = false),
    SimdAny(isPure = false),
    SimdIsFirst(isPure = false),
    SimdActiveThreadsMask(isPure = false),
    QuadBroadcast(isPure = false),
    QuadShuffle(isPure = false),
    QuadShuffleXor(isPure = false),
    TextureSample(isPure = false),
    TextureSampleCompare(isPure = false),
    TextureGather,
    TextureGatherCompare,
    TextureRead(isPure = false),
    TextureWrite(isPure = false),
    TextureSize,
    TextureLevels,
    TextureSamples,
    TextureCalculateLod(isPure = false),
    AtomicLoad(isPure = false),
    AtomicStore(isPure = false),
    AtomicExchange(isPure = false),
    AtomicCompareExchange(isPure = false),
    AtomicAdd(isPure = false),
    AtomicSub(isPure = false),
    AtomicAnd(isPure = false),
    AtomicOr(isPure = false),
    AtomicXor(isPure = false),
    AtomicSMin(isPure = false),
    AtomicSMax(isPure = false),
    AtomicUMin(isPure = false),
    AtomicUMax(isPure = false),
    AtomicFAdd(isPure = false),
    Sincos(isPure = false),
    Modf(isPure = false),
    Frexp(isPure = false),
    LengthSquared,
    DistanceSquared,
    Min3,
    Max3,
    Median3,
    MadHi,
    MadSat,
    Mul24,
    Mad24,
    Select,
    MemoryFence(isPure = false),
    IsFunctionConstantDefined,
}
